### ISSUE TITLE
Do you have plan to update Angular to latest version?

### ISSUE THREAD

**Issue by TonyWoo** [DevArchitecture/DevArchitecture#107]
Do you have plan to update Angular to latest version? Thank you.

**Comment by keremvaris** [comment]
Unfortunately, no. because the angular project is just a demo project for DevArhitecture that we want to show its features. We do not approve of its use on any real product platform. However, if you wish, you can contribute by sending PR to our repo. Thank you for your contribution and interest. @TonyWoo @Bazeel-Waris

**Comment by Bazeel-Waris** [comment]
> Do you have plan to update Angular to latest version? Thank you.

yes
